In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
import matplotlib.pyplot as plt

In [2]:
#Importing data
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep = ';')

In [3]:
#dividing dependent and independent feature.
X = df[list(df.columns)[:-1]]
y = df['quality']

In [4]:
#Spliting in to test and training data.
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [5]:
#Linear regression
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, normalize=False)

In [6]:
#predicting on test dataset
predicted_lin = regr.predict(x_test)

In [7]:
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean square error
print("Residual sum of squares: %.2f"
      % np.mean((regr.predict(x_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regr.score(x_test, y_test))

('Coefficients: \n', array([  1.15989956e-01,  -1.80466188e+00,  -1.50084077e-02,
         9.67717990e-02,  -4.22336380e-01,   5.11799045e-03,
        -2.40509546e-04,  -2.01070812e+02,   8.69262672e-01,
         6.58085048e-01,   1.28438281e-01]))
Residual sum of squares: 0.61
Variance score: 0.25


In [8]:
predicted_lin

array([ 5.57971783,  5.45994641,  6.08955775, ...,  6.37422419,
        6.02965649,  6.01060053])

In [9]:
print metrics.r2_score(y_test,predicted_lin)

0.248156625876


In [10]:
print metrics.mean_absolute_error(y_test,predicted_lin)

0.608501723186


In [11]:
#alpha=0.0001,n_iter=1000
from sklearn import linear_model
np.random.seed(0)
clf = linear_model.SGDRegressor()
clf.fit(x_train, y_train)

ValueError: Floating-point under-/overflow occurred at epoch #1. Scaling input data with StandardScaler or MinMaxScaler might help.

In [23]:
sgd_predicted = clf.predict(x_test)

In [24]:
sgd_predicted

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [25]:
# The coefficients
print('Coefficients: \n', clf.coef_)
# The mean square error
print("Residual sum of squares: %.2f"
      % np.mean((clf.predict(x_test) - y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % clf.score(x_test, y_test))

('Coefficients: \n', array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]))
Residual sum of squares: nan


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [26]:
print metrics.r2_score(y_test,predicted_lin)
print metrics.mean_absolute_error(y_test,predicted_lin)

0.248156625876
0.608501723186


In [ ]:
#######################################

In [41]:
from sklearn import linear_model
clf1 = linear_model.Ridge(alpha=0.01,max_iter=1000)
clf1.fit(x_train, y_train)

Ridge(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, solver='auto', tol=0.001)

In [42]:
sgd_predicted_ridge = clf1.predict(x_test)

In [43]:
sgd_predicted_ridge

array([ 5.5230426 ,  5.47879309,  6.02637981, ...,  6.36201582,
        6.17598876,  5.91458263])

In [44]:
print metrics.r2_score(y_test,sgd_predicted_ridge)

0.249135708772


In [ ]:
##########################################

In [37]:
from sklearn import linear_model
clf2 = linear_model.Lasso(alpha=0.01,max_iter=1000)
clf2.fit(x_train, y_train)

Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute='auto', tol=0.0001,
   warm_start=False)

In [38]:
sgd_predicted_lasso = clf2.predict(x_test)

In [39]:
sgd_predicted_lasso

array([ 5.54672619,  5.53846651,  5.98019329, ...,  6.36551943,
        6.23666966,  6.15811982])

In [40]:
print metrics.r2_score(y_test,sgd_predicted_lasso)

0.222657154219
